### ISSUE TITLE
Couldn't init chrome drivers'str' object is not callable

### ISSUE THREAD

**Issue by virusAl7rbi** [aymannc/EgyBest-Downloader#2]
i fix the old problem but show this to me 
**output**
```
Couldn't init chrome drivers'str' object is not callable
Driver already closed
Driver already closed

 Exited init_chrome
```

**Comment by aymannc** [comment]
You should wait for future updates, the latest commit is 9 months old.
I don't think that the app is still working due to the changes to "EgyBest.com".
Even if you fixed this one, more problem will keep popping up

**Comment by aymannc** [comment]
I've updated the code, you can check the new version
